trigger:
- feature/azure_build

pool:
  vmImage: windows-2022

steps:
- script: |
    echo on
    dir
    git clone https://github.com/DrTimothyAldenDavis/SuiteSparse.git SuiteSparse
    cd SuiteSparse
    git checkout v5.11.0
  displayName: 'Download Suitesparse git'

- script: |
    cd vs-suitesparse\src
    MSBuild.exe .\SuiteSparse.sln /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=x64
  displayName: 'Build'
