trigger:
- feature/azure_build

pool:
  vmImage: windows-2022

variables:
  solution: 'src/SuiteSparse.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  suitesparse: 'v5.11.0'
  libf2c: 'https://github.com/albertony/libf2c/releases/download/v1.1/libf2c.zip'

steps:
- script: |
    echo on
    dir
    cd src
    git clone https://github.com/DrTimothyAldenDavis/SuiteSparse.git SuiteSparse
    cd SuiteSparse
    git checkout $(suitesparse)
  displayName: 'Download Suitesparse git'

- script: |
    choco install wget unzip
    cd vs-suitesparse\libs
    wget $(libf2c)
    unzip libf2c.zip
    dir
    dir x64
  displayName: 'Get libf2c'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true
