trigger:
- feature/azure_build

pool:
  vmImage: windows-2022

variables:
  solution: 'src/SuiteSparse.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  suitesparse: 'v5.11.0'

steps:
- script: |
    echo on
    dir
    cd src
    git clone https://github.com/DrTimothyAldenDavis/SuiteSparse.git SuiteSparse
    cd SuiteSparse
    git checkout $(suitesparse)
  displayName: 'Download Suitesparse git'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

steps:
- script: |
    echo on
    echo %Build.SourcesDirectory%
    dir
    dir src
    cd src
    dir x64
    cd x64
    dir Release
    cd Release
    dir
  displayName: Dir'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'src/$(BuildConfiguration)/Release/?(*.dll|*.lib)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop